#############################################################################
################################ CRUD FAMILY ################################

### Busca uma família

GET  http://localhost:3000/api/family/ HTTP/1.1

### Registra uma família

POST  http://localhost:3000/api/family HTTP/1.1
Content-Type: application/json

{
    "surname": "Doe"
}

### Atualiza a família

PUT  http://localhost:3000/api/family/ HTTP/1.1
Content-Type: application/json

{
    "surname": "DoeDoe"
}

### Remove a família

DELETE http://localhost:3000/api/family/ HTTP/1.1